apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-repo-deployment
  labels:
    app: sample-repo
spec:
  replicas: 2   # run 2 pods for availability
  selector:
    matchLabels:
      app: sample-repo
  template:
    metadata:
      labels:
        app: sample-repo
    spec:
      containers:
      - name: sample-repo-container
        image: nithinmys/sample-html:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sample-repo-service
spec:
  selector:
    app: sample-repo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
